version: "3.7"

services:
  arangodb:
    container_name: arangodb
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: secret
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
