version: '3.7'

services:
  minio:
    container_name: minio
    image: 'minio/minio:latest'
    ports:
      - '9090:9000'
    volumes:
      - data:/data
    environment:
      - MINIO_ACCESS_KEY=secret123
      - MINIO_SECRET_KEY=secret123
    command: minio server /data/minio/
volumes:
  data:
